name: idd-figures
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - xarray
  - jupyter
  - ipykernel
  - geopandas
  - rasterio
  - cartopy
  - shapely
  - pyproj
  - scipy
  - scikit-image
  - scikit-learn
  - pip
  - pip:
    - shiny
    - poetry