name: idd-figures
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - xarray
  - jupyter
  - ipykernel
  - pip
  - pip:
    - shiny
    - poetry